include/lttngh/LttngHelpers.h, include/tracelogging/TraceLoggingProvider.h
Overview:
- Fix compile error under C, where cds_list_head() won't work (for
multiple reasons).
- Events where keyword == 0 sometimes need to be matched by event
filters, so add an event suffix ";k;" that means keyword == 0.
- Use the wchar_t support from LttngHelpers.h instead of duplicating.
This is actually more code than duplicating, but I think it is easier to
follow and it consolidates the wchar_t handling where it belongs.
Details:
- Instead of having wchar_t be an instance of CharNN, make it a special case
(like char already is).
- Because char and wchar_t are now more similar, instead of putting macros
in order char, char16, char32, wchar_t, put them in order char, wchar_t,
char16, char32.
- Add suffix ";k;" when keyword == 0.
- Add C++ helpers for wchar_t: …
=> TraceLoggingProvider.h - keyword 0, wchar_t, fix C

include/lttngh/LttngHelpers.h
Previously, LttngHelpers.h would pass down an alignment characterisc of the input data, rather than the eventual UTF8 output.
Fix this by targeting the required alignment of either the UTF8 string or the uint16_t that will prepend sequences.
=> Fix LttngHelper alignment for strings when ring buffer align is enabled

CMakeLists.txt, azure-pipelines.yml, cmake/modules/AliasPkgConfigTarget.cmake, cmake/modules/Findlttng-ust-tracepoint.cmake, cmake/modules/traceloggingConfig.cmake, src/CMakeLists.txt
- Remove nonstd::string_view and require C++17
- Allow using Catch2 from install
- Support install of tracelogging better
- Find LTTNG dependencies better
- Change pipeline to 18.04
=> Improve dependency finding and install

include/tracelogging/TraceLoggingProvider.h
Add the two missing macros "TraceLoggingUtf8String" and "TraceLoggingCountedUtf8String". Support for these is trivial as TraceLoggingString already assumes utf8 strings.
=> Add support for TraceLoggingUtf8String and TraceLoggingCountedUtf8String

include/tracelogging/TraceLoggingProvider.h
Bug in TraceLoggingEventEnabled that only occurs if the event has a
keyword.
`TraceLoggingEventEnabled(ProviderSymbol, "EventName")` needs to look up
the requested event. Events are identified by a
"ProviderName:EventName;KeywordSuffix" string.
TraceLoggingEventEnabled is supposed to work by creating a
"ProviderName:EventName" string, doing a prefix match on the event, and
if the prefix match succeeds, we check that the next character is a ';'
(meaning we matched up to the keyword prefix) or a 0 (meaning we matched
the full event string).
The bug is that it creates a "ProviderName:EventName;k;" string.
This successfully matches as long as the event has no keywords, but it
incorrectly fails to match if the event does have any keywords.
Fix is to cut off the 3 characters ";k;" after …
=> TraceLoggingEventEnabled - fix for events with keywords

CMakeLists.txt, README.md, include/lttngh/LttngHelpers.h, include/tracelogging/TraceLoggingProvider.h, src/LttngHelpers.c, test/CMakeLists.txt, test/TestTraceLogging.c, test/TestTraceLogging.cpp, test/TestTraceLogging.h
lttng-ust 2.13 is a major breaking change and requires significant
updates to the LttngHelpers and TraceLoggingProvider libraries.
OPEN ISSUE:
- CMake's LTTngUST package is not picking up the new lttng-ust-common
library. For now, if building 2.13+, you must edit CMakeLists.txt to add it.
Overview of changes in LTTNG-UST 2.13:
- Many LTTng symbols were renamed.
- Sequence no longer includes the length field. Instead, the sequence
field references the length field by name.
- Most of the structs are now designed to be versionable, i.e. they start
with a size.
- The lttng_type field has been split into separate structs, which are
related via C-style inheritance (shared initial field which is a
discriminator enum value).
- The field descriptor now stores an `lttng_type_common*` by reference …
=> Support for lttng-ust 2.13+

include/lttngh/LttngHelpers.h, include/tracelogging/TraceLoggingProvider.h, src/LttngHelpers.c
- tracepoint class struct factored out of event
- enum entry requires a probe
=> Fixes for lttng 2.13rc2

include/lttngh/LttngHelpers.h, include/tracelogging/TraceLoggingProvider.h, src/CMakeLists.txt, src/LttngActivityHelpers.c, src/LttngNetHelpers.c, test/CMakeLists.txt, test/TestTraceLogging.h
LTTNG does not have native types for IPv4 addresses, IPv6 addresses, or
sockaddr. Add indirect support - these objects will be converted to
strings before being added to the trace.
- Add LttngHelpers APIs to format these types.
- Add TraceLoggingProvider.h support for these types, including new
macros for IPv4 and IPv6.
- Add tests.
=> Log strings for IPv4, IPv6, sockaddr

include/tracelogging/TraceLoggingProvider.h, test/TestTraceLogging.h
Rename the new IP address macros:
- TraceLoggingIPv4 renamed to TraceLoggingIPv4Address.
- TraceLoggingIPv6 renamed to TraceLoggingIPv6Address.
=> TraceLoggingIPv4Address - rename

src/LttngHelpers.c
It has been brought up that these LTTNG helpers are pretty close to being compilable in C++ mode, if not for a few casts that are the result of language/compiler differences.
These changes aren't very intrusive and let you run this project through g++ now.
=> g++ compatibility: Explicit casts

cmake/modules/FindLTTngUST.cmake, src/LttngHelpers.c
This PR makes the following changes: 
- Adds a local custom `FindLTTngUST.cmake`. 
- This file contains the FindLTTngUST  version component extraction fix from https://github.com/Kitware/CMake/commit/4ce5765a8605cf4aa0fbb01f77ae2bf764452ccd.
- Additionally it conditionally adds `liblttng-ust-common.so` to LTTngUST link libraries for LTTng 2.13+
- it switches `lib_ring_buffer_align*` calls to `lttng_ust_ring_buffer_align*`
=> Fixing LTTng version issues and adding `liblttng-ust-common.so` for LTTng 2.13+

etw/TraceLoggingDynamic_CPP/TraceLoggingDynamic.h
Update the SAL annotations in TraceLoggingDynamic.h to use the recommended
SAL 2 constructs. Fixes #36
=> Update SAL annotations in TraceLoggingDynamic.h

LTTng/README.md, LTTng/include/tracelogging/TraceLoggingProvider.h
Add documentation to TraceLogging for LTTng which discourages its use from within inline functions.
=> LTTng: Document Inline Function Limitation

LTTng/include/lttngh/LttngHelpers.h, LTTng/src/LttngNetHelpers.c
lttngh_FormatIPv6 requires a buffer of size 46, which is "max IPv6 format length". 46 matches the behavior of inet_ntop.
Nominally, our constant should match the value of `INET6_ADDRSTRLEN`, which is the commonly-used constant for "max IPv6 format length". Recent versions of Linux have increased the value to 48 to account for some formatters that add `[...]` around the address. So this PR updates the LTTNGH constant to match.
This isn't really necessary because inet_ntop doesn't add the `[...]` around the address, so it's max is still 46. But to avoid confusion, our constant should match.
=> Sometimes INET6_ADDRSTRLEN is 48

etw/cs/traceloggingdynamic/TraceLoggingDynamic.cs, etw/cs/traceloggingdynamic/tests/Program.cs
Create ways for the user of TraceLoggingDynamic.cs to get better performance.
1. Most of the time is spent in Encoder.UTF8.GetBytes (converting event/field name strings into bytes). Allow the user to supply an alternate Encoder that is used for event/field name encoding.
2. Add overloads for the ANSI string methods that accept a string value and an encoder, making it more convenient/efficient for the user to log ANSI strings. (Existing overloads accept value as `byte[]`, requiring the user to have done their own encoding into their own buffer.)
3. Add a SetStructFieldCount method so that the field count can be set after the struct fields are added rather than before. Usage pattern is to call `position = AddStruct("StructName", 1)` (where 1 is a placeholder value), then after the fields …
=> Performance enhancements for TraceLoggingDynamic.cs

etw/cs/traceloggingdynamic/TraceLoggingDynamic.cs, etw/cs/traceloggingdynamic/tests/Program.cs
- Add a GetRawFields method that returns a copy of fields currently in
the builder.
- Add an AppendRawFields method that appends fields extracted via
GetRawFields.
- Rename the Latin1 class to UncheckedASCIIEncoding and implement the
rest of it so it is safe for general use.
- Add some validation of the new GetRawFields and AppendRawFields methods.
- Change how the test code uses SetStructFieldCount so it is more
obvious what is happening.
=> Add AppendRawFields, extend the UncheckedASCII sample

etw/rust/tracelogging/Cargo.toml, etw/rust/tracelogging/src/_internal.rs, etw/rust/tracelogging/src/lib.rs, etw/rust/tracelogging/src/native.rs, etw/rust/tracelogging/tests/tests.rs, etw/rust/tracelogging_dynamic/Cargo.toml, etw/rust/tracelogging_dynamic/src/lib.rs, etw/rust/tracelogging_dynamic/tests/tests.rs, etw/rust/tracelogging_macros/Cargo.toml, etw/rust/tracelogging_macros/src/event_generator.rs, etw/rust/tracelogging_macros/src/field_option.rs, etw/rust/tracelogging_macros/src/strings.rs
- Add a `filetime_from_systemtime!(systemTime)` macro. Export it from both tracelogging and from tracelogging_dynamic crates. Note that we're using a macro so that the tracelogging and tracelogging_dynamic crates do not become dependent on the `std` crate.
- As an optimization, split the `filetime_from_duration(dur, after)` function into two functions - one for after == true and one for after == false.
=> rust: add filetime_from_systemtime macro

etw/rust/tracelogging/Cargo.toml, etw/rust/tracelogging/src/lib.rs, etw/rust/tracelogging/tests/tests.rs, etw/rust/tracelogging_dynamic/Cargo.toml, etw/rust/tracelogging_dynamic/src/builder.rs, etw/rust/tracelogging_dynamic/src/lib.rs, etw/rust/tracelogging_dynamic/src/provider.rs, etw/rust/tracelogging_dynamic/tests/tests.rs, etw/rust/tracelogging_macros/Cargo.toml, etw/rust/tracelogging_macros/src/lib.rs
- Rename `filetime_from_systemtime` to `win_filetime_from_systemtime`.
- Improve the doc comments for win_filetime_from_systemtime.
- Define `Debug` trait on `EventBuilder`.
- Define `Debug` trait on `ProviderOptions`.
- Remove "For testing" macros from `tracelogging_macros`.
- Version 1.0.2.
=> rust tracelogging - Debug trait, rename macro, fix docs

etw/rust/tracelogging/Cargo.toml, etw/rust/tracelogging/src/native.rs, etw/rust/tracelogging_dynamic/Cargo.toml, etw/rust/tracelogging_macros/src/provider_generator.rs
**Why**
`tracelogging` crate cannot be used in kernel-mode code because of the reliance on Win32 APIs such as `EventRegister`.
**What Changed**
* Added optional `kernel_mode` feature which replaces Win32 APIs with kernel-mode APIs like `EtwRegister`
* Added optional `user_mode` feature for enabling Win32 APIs which is set by default to keep in parity with the existing configuration.
* Made provider static variable public for use across different files in the program.
**How Tested**
Added it to a kernel-mode driver built using [windows-drivers-rs](https://github.com/microsoft/windows-drivers-rs) and tested tracelogging prints on WinDbg.
**Usage**
Enabling `kernel_mode` feature will require the client to link with `NtosKrnl.lib` for definition of `Etw*` APIs.
=> Added kernel_mode and user_mode features in tracelogging crate

etw/python/traceloggingdynamic/traceloggingdynamic.py
Fix exception on older builds of python where the algorithm-specific constructors don't recognize the usedforsecurity parameter. Fix by using the generic constructor which ignores unrecognized parameters. #58
=> traceloggingdynamic.py - fix exception on old python

etw/rust/tracelogging_macros/src/event_generator.rs
Mitigates a new-ish clippy lint: https://rust-lang.github.io/rust-clippy/master/index.html#repr_packed_without_abi
=> Specify C-ABI explicitly for `packed` structs

etw/cpp/traceloggingdynamic/TraceLoggingDynamic.h
Fixed below error when compiling by clang-cl.exe on Windows, here is the original issue https://github.com/open-telemetry/opentelemetry-cpp/issues/3237.
```
TraceLoggingDynamic.h(2144,31): error: invalid bitwise operation between different enumeration types ('Type' and 'tld::InType')
2144 |             _tld_ASSERT((type & InTypeMask) == (type & 0xff), "InType out of range");
```
=> Fix build error of invalid bitwise operation between different enumerator types
